### ISSUE TITLE
PPoPP 2019 Rainey talk 

### ISSUE THREAD

**Issue by rrnewton** [wonks/Talk_Rehearsal_Feedback#13]
Leave comments below.

**Comment by rrnewton** [comment]
Slide numbers!  They help with making comments like these.

**Comment by ccshan** [comment]
Watch http://www.nancyhoufek.com/videos.shtml

**Comment by ccshan** [comment]
It looks like the Fcost on the slide should come 3rd, not 1st, to match your spoken statement about what's in spguard.

**Comment by ccshan** [comment]
Your final slide should contain your most important message, which is probably not the related/future work.

**Comment by akuhlens** [comment]
- There were many bullets. I ended up reading most of them, and giving up on some of them.
- Try to remain focused on the message of each slide.
    - When you are describing alpha and kappa you get into details of the implementation such as using CAS in `spguard`. 
- The cognitive load for describing the algorithm and its bounds is really high. Maybe pictures or starting with the most general picture, and then zooming in on most important points may help.
- Might be interesting to add the performance increase from sequential to the performance comparison. There was no context to make it obvious that the results should be considered the same.

**Comment by rrnewton** [comment]
#### "Granularity control is a balancing act"

Info-rate:
Lots of info on this slide, and it appears all at once.

On this slide you talk about switching to a different algorithm, but
the visualization doesn't SHOW that, it shows the *same* colored circles
in a different arrangement.


#### "Related work & ..."

Too much text!

This is kind of insider baseball.  I doubt all of the audience in
wonks is following all of it.  PPoPP audience might know most of this
work.


#### "SP guard"

 * slightly confusing that the args are described out of order,
   i.e. F_cost described last.

 * What is the "F" for in "Fcost",  why not just "cost"?

#### "Challenge:.."

Lots of these slides are text heavy, but this one especially so...

#### "our .. algorithm"

Can't we visualize a lot of this process?  Reading cycle counters,
ranges of time, ... It is a *dynamic* process, so it can be animated.

[- Ken Shan later mentions a stream of trucks going under a bridge
estimating the clearance... then he came up with packages coming down
a conveyer belt.  I love the UPS example because it is in fact an
amortization problem.  Sending a box with one tiny item in it is
wasteful... there is a mimimum sized carboard box you can send also.
-]

#### "Cost model ..."

This part you do visualize, but this is the part that almost 100% of
ppopp ppl *will* understand, right?

#### "Bound for ..."

Hmm, since the talk is just the advertisement for the paper, I don't
know if it should try to communicate the bound itself at all.  It
could just highlight the qualitative result, and refer to the paper.

#### "Benchmarking ..."

This part seems accessible

Colorize per benchmark ... 

#### "Conclusion"

This is great.. but I think these same points could have been made in
a punchy form back in the "related work" part of the talk (and then
just repeated here).

What does "state of the art implementation" mean here... that sounds
vague / like hype.

Questions
--------------------------------------------------

SamTH: what would the original WS bound be like if you incorporated
\tau there?  Ans: extra tau on the work term, also increases span.

RN: methodology - Average of 30 trials...

Feedback round:
--------------------------------------------------

 * Code highlight. Syntax coloring.  Long code on spguard.

 * Confused about the work/span DAG picture.  Thought the programmer
   had to construct this...

 * highlight more of YOUR work (separating from general background)

 * Baojun: why is there only one spawn (one-armed) instead of two.

 * Matthew: would like to see bookends on the talk / big picture
   beginning end & sign posting

 * Vollmer: lost on big picture at the time we got to evaluation.
   (Matthew: you did some of the explaining in benchmarks in speech,
   but visualization doesn't follow.)

 * Tori: maybe add more colors, more visually interesting.

 * RyanS: Dense.  Talks about highlighting bullets using
   transparency/opacity to highlight the current one.

 * Kyle: cognitive load.  Section on algorithm was especially bad.
   I was unfamiliar with the term "granularity control".

 * Chai: benchmark graph was also confusing

 * Density (again) too much info.  Completely lost for those big text
   parts.

 * Ken: how would you explain this on the whiteboard?  Would probably
   come up w some good (visualization) strategies.


 * Andre: were discussing alpha and kappa and made a comment about CAS
   and that seemed extraneous at the time.

 * Ambrose: beginning "granularity control" ... then lost, then only
   came back at performance results.  The whole time through he didn't
   really understand the point.

 * SamTH: in addition to pictures, REAL examples would be nice.  "Map"
   was disappointing, because you can't run the program on the slide
   and see anything happen.  In other places there are just example
   parallel skeletons instead of code.  Even if it's parfib, it's
   better to have something concrete.
   - Concrete programs w concrete granularity control.  Fine.
   - Concrete program, but with Map factored, now manual is not
     feasible.
   - 

 * RN: aspect ratio!  They're widescreen now.
 * Standard stuff: 
   - info per slide, don't show us your notes, etc.  More visualization.
   - delete 75% of the info in this talk!
   - people understand less than you think, and that's true  even when
     you take into account this law!
