### ISSUE TITLE
2019 PLDI Vollmer practice talk on Gibbon/LoCal

### ISSUE THREAD

**Issue by rrnewton** [wonks/Talk_Rehearsal_Feedback#14]
leave comments!

**Comment by ccshan** [comment]
"LoCal binding forms for regions and locations" slide: right-hand side should be pictures showing regions as rectangular bars and locations as arrows pointing into those bars.

**Comment by ccshan** [comment]
Slide 10, the 3 bullets should become shaded/bracketed parts of a region depicted as a horizontal bar.

Same with the 4 bullets on slide 11.

**Comment by ccshan** [comment]
And on slide 12, lines of code should be connected by arrows to parts of a region schematically depicted as a horizontal bar.

**Comment by ccshan** [comment]
Serious question, what's the difficulty preventing each table row on slide 13 from being a picture (which can be understood without chasing nonce names), as discussed after a previous talk about Gibbon?

**Comment by ccshan** [comment]
End talk with "thank you"

**Comment by samth** [comment]
1. Don't use haskell notation.
2. Make code larger
3. Avoid transitions
4. What's the capnproto/protobuf/etc serialization of that tree.
5. Make all the fonts larger!
6. *What is the big idea?*
7. So much text
8. What is the difference between Gibbon and Ours?
9. Don't end with "any questions"
10. Have a final slide with some takeaways.

**Comment by rrnewton** [comment]
s5: doesn't mention "not type safe" when talking about how the C code is bad.

  - "animal that climbs trees": Gibbons are more than that!  They're
    tied for fastest tree traversal at 35 mph.

s7 - too little time to process all that code (for building tree)
 - better to show ONE constructor probably...

s8 goes through line by line which is much better.  Don't really need
the 1st code dump then do we?

s11 - hmm.. doing the operational bit AFTER walking through the code.
Maybe it should be in the opposite order?  The operational
walkthrough, updating memory step-by-step, is the more accessible
part.

s12 - "the type system tracks all of this or Node would not typecheck"
is a powerful argument on this slide.

Question: How much code did people unfamiliar (vikraman?) understand from
  the examples?

I think the two plots (Racket node counting, JSON).
But I think Table 1 is actually somewhat more compelling.
The data should be put in a new form to present that well.

 * Some foreshadowing would be good to emphasize that performance is
   the reason we want to do all this stuff on serialized data in the
   first place.

**Comment by rrnewton** [comment]
Feedback round notes:
---------------------

Rainey: be precise around the actual guarantees, mention type safety.

  perf slides: say at a high level what it's doing and why its faster.

RyanS: also wants more example of what would be error prone about the C code.

Vikraman: region type systems from the 90s: have a slide that mentions
if there is region inference, relating to that earlier work.

Ken Shan -- too much space inbetween each letter.
  - consistent visual language of how memory is depicted.
  - type checking slide -- use pictures there too
  - phrase "producing data" (text allowed on slide, not full sentence)
    example of what to put on slide
  - the reason to switch examples is to go from consuming to producing

Tori: too much text.
SamTH: way too much text, have pictures.
 - clarify what idea you're trying to communicate
 - one technical idea per conference talk
 - "We can use region-like type systems to verify this low level
    C style code."
 - in the context of Gibbon, we want this for correct compiler
   construction.
   - Ken would actually like to put up that thesis sentence.
     (maybe even highlight parts of that)

 - could show more C code... alternate between that and the Local.
   do everything you can to make it easier to read.

RN: argues for single bar graph for evaluation.
Ken: maybe that evaluation slide should go at the beginning.
     "turns out this produces huge performance wins"

Chai: foreshadowing.  "RouteEnds" seemed like a rough transition.

Sarah: 1st slide had text about the tree traversal, didn't like how it
dived right in.

**Comment by rrnewton** [comment]
### Practice talk 2

Intro slide needs BRANDING (IU/Purdue logos)

I really like the "Functions on serialized data" slide.

Love the transition from FUNCTIONS to PROGRAMS

Why do tree manip benchmarks not include the Racket AST or the
twitter/JSON programs?

"CNF" => "Haskell Compact Form"

A bit too much time on eval... could merge in the twitter slide to the
bargraphs.  Either take one data point or geomean of those datapoints.

I love all these examples with only one line of code!

Didn't use the word "linearity" on the "letloc" introduction slide.

I love letloc in action!!

The green highlights should be more visible!

You don't want to use the "Forall" symbol for the quantifier?

"Random access pattern matches": 2 solutions, but does "LoCal" let us
express both of these things, or does the LoCal implementation
(compiler) provide both options?


Indirections... this didn't have much foreshadowing.  It falls under
EFFICIENCY... but how many sub-bullets are in there.

Then it jumped straight to conclusion.

Artifact Link??

-----------

Mike: inverted ordering of explanation.. want to say what you want to
do and then how.

Mike -- could have a slide on asymptotic efficiency.
