### ISSUE TITLE
Shan & Ramsey, Exact Bayesian inference by symbolic disintegration

### ISSUE THREAD

**Issue by ccshan** [wonks/Talk_Rehearsal_Feedback#2]
Please feel free to post your feedback on my talk as comments here. Thanks!

**Comment by dpthurst** [comment]
It looks like the slides are running off the edge. Aspect ratio issue?

**Comment by dpthurst** [comment]
Your highlighting doesn't jump out that much; perhaps the color should be a little less pastel-y
