### ISSUE TITLE
2017 ICFP - Praveen Narayanan

### ISSUE THREAD

**Issue by frenchy64** [wonks/Talk_Rehearsal_Feedback#4]
Leave feedback for the talk in comments on this issue.

**Comment by david-christiansen** [comment]
Putting text on a slide and then hiding it again is frustrating for me as an audience member. (this is the table of similarities)

**Comment by david-christiansen** [comment]
The association between the labels and the variables in y=an+b is not so clear just from the graphics. In particular, "per-iteration cost" looks closer to a than to n.

**Comment by rrnewton** [comment]
Rather than showing the example (running time, linear regression), and *then* saying the approach is actually more general (sounds defensive), perhaps better to say it is general first and then transition via "here's a particular example".

**Comment by david-christiansen** [comment]
Is the bendy left arrow on "Write generative model" the normal Haskell left arrow, or is it some other notation?

**Comment by samth** [comment]
Can you write the input/output so that they look more similar?

**Comment by david-christiansen** [comment]
Why is constrainValue written as a left triangle? Given that it's punctuation, shouldn't it be infix in Haskelly notation, or surrounded in parens? The current one is a bit slow to visually parse.

**Comment by david-christiansen** [comment]
The slide with "posterior distribution" at the bottom of the slide is about where my brain got lost in the code. I lost track of what "factor" means, as well as the history of the code examples shown.

**Comment by cderici** [comment]
Can you find a smaller example? It's a little hard to keep track of all the different stages of the transformation.

**Comment by samth** [comment]
The whole first half of the talk doesn't really make clear what you're adding.

**Comment by david-christiansen** [comment]
I'm still not sure what light blue boxed code means.

**Comment by david-christiansen** [comment]
is plate a binding form? If so, why does it use . instead of -> the way lambda does on your slides?
