### ISSUE TITLE
2017 Haskell Symposium - Chao-Hong Chen

### ISSUE THREAD

**Issue by frenchy64** [wonks/Talk_Rehearsal_Feedback#5]

**Comment by RyanGlScott** [comment]
I'm already lost. What are these data structures supposed to be accomplishing? Where does the choice come up?

**Comment by david-christiansen** [comment]
The contrast between the hard-edged mono code font and the soft textiles in the theme is pretty jarring

**Comment by rrnewton** [comment]
Definitely some more motivation would help before diving in.  Why would we want to change data structures? What are some of the tradeoffs that prevent a one-size-fits-all solution?

**Comment by david-christiansen** [comment]
What are covert functions? Does that mean "conversion functions" or "coercion functions"?

**Comment by RyanGlScott** [comment]
The "Freezable IORef" slide is _very_ cluttered—I'm having difficulty following along with the particular things on that slide. Can you highlight what things you're talking about on a point-by-point basis, perhaps by fading out other things slightly?

**Comment by rrnewton** [comment]
typo: "covert"

Slide titled "Sketch" is really **the big idea** -- it deserves all the fanfare to draw attention to it, as described here:
https://www.microsoft.com/en-us/research/academic-program/give-great-research-talk/
https://www.cis.upenn.edu/~sweirich/talks/plmw15-giving-a-talk.pdf

"Freezable IORef slide" -- waaaay too much code.  Immediately lost.

**Comment by rrnewton** [comment]
As we always harp on ... less code less detail.  It's very hard to underestimate the number of lines of never-before-seen code that the audience can *really* parse on the fly.

**Comment by david-christiansen** [comment]
Don't put the important observation at the bottom of a slide in red like this. In many rooms, the bottom 1/4 of the slide is hard to see due to heads in front of viewers.

**Comment by rrnewton** [comment]
Re: fanfare -- the big idea, and the formal result, is about lock freedom doing double duty.  It avoids blocking, but it ALSO guarantees that intermediate states of the structure are valid -- valid for recovering from crashes (NVRam) and valid for snapshotting and converting (our work).

That main idea needs to be boiled down to a simple slogan and repeated a few times.

**Comment by rrnewton** [comment]
All this business about freezing and different threads in different states is probably better pictured not with code, but with pictures of threads (e.g. wiggly lines) and events in time on those threads.

**Comment by RyanGlScott** [comment]
The formalism slide uses such a tiny font that I doubt anyone is going to be able to read it. Either take the significant parts of the formalism and zoom in on them, or don't use it at all.

**Comment by rrnewton** [comment]
Other propaganda to include for the FP audience is that this is one way to bring the treasured principle of *composability* to lock-free data structures.  You can compose two lock free structures and get a new lock free structure.

(That doesn't work in general, for most notions of composition, so this is kind of special and surprising.)

**Comment by rrnewton** [comment]
Don't end on a slide that just says "thank you" -- end on the conclusions slide with your contact info.

**Comment by rrnewton** [comment]
RyanS: why is the adaptive line below Ctrie?
Ken: is it on hackage?

**Comment by rrnewton** [comment]
It occurs to me that one thing that would really help for our future practice talks is to have various audience members write a one-paragraph "synopsis" the way reviewers do at the beginning of their paper reviews.

This would allow the presenter a measure of the amount of information successfully conveyed (they "goodput", if you will).
