### ISSUE TITLE
2018 UNIF - Weixi Ma on Efficiency of a Good but not Linear Nominal Unification Algorithm

### ISSUE THREAD

**Issue by ccshan** [wonks/Talk_Rehearsal_Feedback#8]

**Comment by samth** [comment]
- too many bullets
- 6 - what is this inference system?
- 9 - how does the algorithm do this?
- 17 - bad title

**Comment by ccshan** [comment]
Don't use a small white mouse pointer with a black outline to point. Ideally you'd use your finger to touch the screen, but that'd probably be difficult in a workshop setting, so add highlighting to your slides, or at least use a large contrasting mouse pointer. A laser pointer is a last resort.

**Comment by ccshan** [comment]
Merge slide 3 until slide 2 and reduce bullets to avoid switching back and forth.

**Comment by ccshan** [comment]
Clarify whether by "de Bruijn numbers" you mean de Bruijn indices or de Bruijn levels.

**Comment by ccshan** [comment]
Bright green (#00FF00) on white is not good for any text.

**Comment by ccshan** [comment]
Consider changing your title on the first slide to just say "virtually linear".
